name: Deploy docs to GitHub Pages
on:
  push:
    branches:
      - master
env:
  CECIL_BASEURL: '/'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build site
      uses: Cecilapp/Cecil-Action@v3
      with:
        config: 'cecil.yml'
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        email: arnaud@ligny.org
