name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - test
env:
  CONFIG: 'cecil.yml'
  CECIL_BASEURL: '/'
  EMAIL: arnaud@ligny.org
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  BUILD_DIR: _site
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build site with Cecil
      uses: Cecilapp/Cecil-Action@composite

    - name: Upload site to Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: _site
        path: _site
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download site from Artifacts
      uses: actions/download-artifact@v1
      with:
        name: _site
    - name: Deploy site to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@2.0.1
